apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    app: traffic-prometheus
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 3s
    scrape_configs:
    - job_name: 'traffic-envoy-pods'
      kubernetes_sd_configs:
      - role: pod
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_traffic_envoy_proxy]
        regex: "[0-9a-z]+"
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_pod_ip]
        regex: (.+)
        target_label: __address__
        replacement: ${1}:{{ .Values.port.envoyAdmin }}
      - target_label: __metrics_path__
        replacement: /stats/prometheus
{{if .Values.monitor.enabled }}
    - job_name: 'traffic-nodes'
      kubernetes_sd_configs:
      - role: node
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __address__
        replacement: ${1}:32466
  {{end}}
