apiVersion: v1
kind: ServiceAccount
metadata:
  name: "traffic-sa"
  labels:
    app: traffic-manager
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
