apiVersion: v1
kind: Service
metadata:
  name: traffic-control
  labels:
    app: traffic-control
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: {{ .Values.port.trafficControl }}
  selector:
    app: traffic-control
