apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: traffic-control
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
  name: traffic-control
spec:
  selector:
    matchLabels:
      app: traffic-control
  template:
    metadata:
      labels:
        app: traffic-control
    spec:
      serviceAccountName: "traffic-sa"
      containers:
      - image: "{{ .Values.images.trafficControl }}"
        imagePullPolicy: Always
        name: traffic-control
        command:
        - "./traffic-control-plane"
        - "-alsologtostderr"
        env:
        - name: TRAFFIC_MANAGE_PORT
          value: {{ .Values.port.trafficControl | quote }}
        - name: ENVOY_PROXY_PORT
          value: {{ .Values.port.envoyProxy | quote }}
        ports:
        - containerPort: {{ .Values.port.trafficControl }}
          protocol: TCP

