apiVersion: v1
kind: Service
metadata:
  name: traffic-zipkin
  labels:
    app: traffic-zipkin
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: traffic-zipkin
  ports:
  - name: zipkin
    port: {{ .Values.port.trafficZipkin }}
    targetPort: {{ .Values.port.trafficZipkin }}
