[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.0"

[[constraint]]
  version = "v0.6.9"
  name = "github.com/envoyproxy/go-control-plane"

[[override]]
  name = "k8s.io/api"
  revision = "73d903622b7391f3312dcbac6483fed484e185f8"
  #version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "302974c03f7e50f16561ba237db776ab93594ef6"
  #version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/client-go"
  #version = "kubernetes-1.10.1"
  revision = "989be4278f353e42f26c416c53757d16fcff77db"

[[override]]
  name = "k8s.io/kubernetes"
  #version = "kubernetes-1.10.1"
  revision = "d4ab47518836c750f9949b9e0d387f20fb92260b"

[[override]]
  name = "k8s.io/apiserver"
  #version = "kubernetes-1.10.1"
  revision = "06e4be4fafa2c9356e02424aac4e714e2ebeff60"
