apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: productpage
    servicePort: 9080
  rules:
  - host: hello.com
    http:
      paths:
      - path: /hello
        backend:
          serviceName: http-text-response
          servicePort: 8080
  - http:
      paths:
      - path: /productpage
        backend:
          serviceName: productpage
          servicePort: 9080          
      - path: /reviews
        backend:
          serviceName: reviews
          servicePort: 9080
      - path: /ratings
        backend:
          serviceName: ratings
          servicePort: 9080
      - path: /api/v1
        backend:
          serviceName: traffic-prometheus
          servicePort: 9090   
      - path: /api/v2
        backend:
          serviceName: traffic-zipkin
          servicePort: 9411 
